# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
ci:
  autoupdate_schedule: quarterly
  skip: ["identity", "uv-lock", "ty", "pytest", "coverage-badge"]

default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["pre-commit"]

repos:
  - repo: meta
    hooks:
      - id: identity

  # Stolen from: https://github.com/elementary-data/elementary/blob/ef5043811a72009126391a3f0c8a18f72ae00b18/.pre-commit-config.yaml
  - repo: local
    hooks:
      - id: no-commit
        name: Check for NO_COMMIT marker
        entry: bash -c "git diff --cached -U0 | (! grep NO_COMMIT)"
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        name: Don't allow commits to the main branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure files end with a newline character
      - id: mixed-line-ending
        name: Align mixed line ending
      - id: check-added-large-files
        name: Check for large files
      - id: check-json
        name: Check JSON files are valid and parseable
        exclude: "devcontainer.json"
      - id: check-yaml
        name: Check YAML files are valid and parseable
      - id: check-toml
        name: Check TOML files are valid and parseable
      - id: check-ast
        name: Validate Python
      - id: detect-private-key
        name: Check for the existence of private keys

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config
        name: Validate pre-commit CI config

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.25
    hooks:
      - id: uv-lock
        name: Check that the lock file is up-to-date

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff-check
        name: Lint Python code
        args: ["--fix"]
      - id: ruff-format
        name: Format Python code

  # https://github.com/astral-sh/ty?tab=readme-ov-file#getting-started
  - repo: local
    hooks:
      - id: ty
        name: Run type checks
        entry: uvx ty check
        language: system
        pass_filenames: true
        always_run: false
        types: ["python"]

  - repo: https://github.com/billwallis/bills-hooks
    rev: v0.0.6
    hooks:
      - id: tidy-gitkeep
        name: Remove redundant .gitkeep files

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.0
    hooks:
      - id: check-github-workflows
      - id: check-compose-spec

  - repo: local
    hooks:
      - id: check-pyproject-schema
        name: Validate pyproject.toml schema
        entry: check-jsonschema
        pass_filenames: true
        language: python
        additional_dependencies: ['check-jsonschema==0.35.0']
        files: pyproject.toml
        args: ["--schemafile", "https://json.schemastore.org/pyproject.json"]
        # This calls a remote URL, so run on pre-push to avoid slowing down commits
        stages: ["pre-push"]

  - repo: local
    hooks:
      - id: pytest
        name: Run unit tests
        entry: uv run pytest tests --quiet
        stages: ["pre-push"]
        language: unsupported
        pass_filenames: false
        always_run: true
      - id: coverage-badge
        name: Generate coverage badge
        entry: uv run coverage-badge -o coverage.svg -f
        stages: ["pre-push"]
        language: unsupported
        pass_filenames: false
        always_run: true
